version: "3.9"

services:
  glass-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: glass_api
    ports:
      - "8000:8000"
    restart: unless-stopped

  glass-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: glass_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://glass-api:8000
    depends_on:
      - glass-api
    restart: unless-stopped
