version: "3.9"

services:
  glass-api:
    image: ghcr.io/gujjar-pranav/glass-identification-api:latest
    container_name: glass_api
    ports:
      - "8000:8000"
    restart: unless-stopped

  glass-app:
    image: ghcr.io/gujjar-pranav/glass-identification-app:latest
    container_name: glass_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://glass-api:8000
    depends_on:
      - glass-api
    restart: unless-stopped
